//This code is hand written
class Character {
  late int charId;
  late String Name;
  late String StatusIfDeadOrAlive;
  late String Species;
  late String Type;
  late String Gender;
  late String Location;
  late String Image;
  late List<String> EpisodeAppearance;

  Character({
    required this.charId,
    required this.Name,
    required this.StatusIfDeadOrAlive,
    required this.Species,
    required this.Type,
    required this.Gender,
    required this.Location,
    required this.Image,
    required this.EpisodeAppearance,
  });

  Character.fromJson(Map<String, dynamic> json) {
    charId = json["id"] ?? 0;
    Name = json["name"] ?? "Unknown";
    StatusIfDeadOrAlive = json["status"] ?? "Unknown";
    Species = json["species"] ?? "Unknown";
    Type = json["type"] ?? "";
    Gender = json["gender"] ?? "Unknown";
    Location = json["location"]?["name"] ?? "Unknown";
    Image = json["image"];
    EpisodeAppearance = List<String>.from(json["episode"] ?? []);
  }
}

/* This Following code is generated by an online tool */
// class Characters {
//   int? id;
//   String? name;
//   String? status;
//   String? species;
//   String? type;
//   String? gender;
//   Origin? origin;
//   Origin? location;
//   String? image;
//   List<String>? episode;
//   String? url;
//   String? created;
//
//   Characters(
//       {this.id,
//         this.name,
//         this.status,
//         this.species,
//         this.type,
//         this.gender,
//         this.origin,
//         this.location,
//         this.image,
//         this.episode,
//         this.url,
//         this.created});
//
//   Characters.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     status = json['status'];
//     species = json['species'];
//     type = json['type'];
//     gender = json['gender'];
//     origin =
//     json['origin'] != null ? new Origin.fromJson(json['origin']) : null;
//     location =
//     json['location'] != null ? new Origin.fromJson(json['location']) : null;
//     image = json['image'];
//     episode = json['episode'].cast<String>();
//     url = json['url'];
//     created = json['created'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['status'] = this.status;
//     data['species'] = this.species;
//     data['type'] = this.type;
//     data['gender'] = this.gender;
//     if (this.origin != null) {
//       data['origin'] = this.origin!.toJson();
//     }
//     if (this.location != null) {
//       data['location'] = this.location!.toJson();
//     }
//     data['image'] = this.image;
//     data['episode'] = this.episode;
//     data['url'] = this.url;
//     data['created'] = this.created;
//     return data;
//   }
// }
//
// class Origin {
//   String? name;
//   String? url;
//
//   Origin({this.name, this.url});
//
//   Origin.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     url = json['url'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['name'] = this.name;
//     data['url'] = this.url;
//     return data;
//   }
// }
